const DIGITAL_BANKING_NODES = [
  ['KOTLIN', 'mobile', 'Customer Android app', 'Secure mobile banking access', 'smartphone'],
  ['SWIFT', 'mobile', 'Customer iOS app', 'Secure mobile banking access', 'smartphone'],
  ['REACT', 'frontend', 'Customer web banking', 'Responsive account management', 'react'],
  ['OPERATIONS_CONSOLE', 'frontend', 'Support operations console', 'Disputes compliance and support', 'layout-dashboard', 'React', 'Internal operations workspace'],
  ['KEYCLOAK', 'auth', 'Identity MFA and SSO', 'OAuth MFA and regional identity', 'shield'],
  ['API_GATEWAY', 'backend', 'Secure API gateway', 'Rate limits and request routing', 'server', 'Go', 'Low-latency edge routing'],
  ['CUSTOMER_PROFILE_SERVICE', 'backend', 'Customer profile service', 'Profiles KYC and residency', 'server', 'Java', 'Transactional customer workflows'],
  ['WALLET_SERVICE', 'backend', 'Multi-currency wallet service', 'Balances holds and limits', 'wallet-cards', 'Java', 'Balance and limit orchestration'],
  ['LEDGER_SERVICE', 'backend', 'Double-entry ledger service', 'Strictly consistent money movement', 'book-open-check', 'Java', 'Strongly consistent money state'],
  ['CARD_AUTHORIZATION_SERVICE', 'backend', 'Card authorization service', 'Realtime card decisions', 'credit-card', 'Go', 'Low-latency decision engine'],
  ['TRANSFER_SERVICE', 'backend', 'Bank transfer service', 'ACH SEPA and local rails', 'landmark', 'Java', 'Rail-specific workflow execution'],
  ['PAYMENT_ORCHESTRATOR', 'backend', 'Payment orchestration service', 'Provider routing and retries', 'workflow', 'Go', 'Provider failover coordination'],
  ['FRAUD_ENGINE', 'backend', 'Realtime fraud engine', 'Risk scoring and controls', 'shield-alert', 'Python', 'Model-driven scoring paths'],
  ['COMPLIANCE_SERVICE', 'backend', 'Compliance screening service', 'AML sanctions PCI GDPR', 'badge-check', 'Java', 'Policy screening and evidence'],
  ['DISPUTE_SERVICE', 'backend', 'Dispute handling service', 'Chargebacks evidence and resolution', 'scale', 'Java', 'Case and evidence workflows'],
  ['RECONCILIATION_SERVICE', 'backend', 'Settlement reconciliation service', 'Ledger provider consistency checks', 'refresh-cw', 'Python', 'Batch consistency analysis'],
  ['SCHEDULED_PAYMENTS_SERVICE', 'backend', 'Scheduled payments service', 'Durable recurring payment execution', 'calendar-clock', 'Go', 'Durable delayed execution'],
  ['NOTIFICATION_SERVICE', 'backend', 'Customer notification service', 'Transactional delivery and preferences', 'bell-ring', 'Go', 'High-volume fan-out delivery'],
  ['AUDIT_LOG_SERVICE', 'backend', 'Immutable audit log service', 'Tamper-evident compliance events', 'scroll-text', 'Java', 'Append-only audit ingestion'],
  ['REPORTING_SERVICE', 'backend', 'Regulatory reporting service', 'Jurisdiction reports and exports', 'file-chart-column', 'Python', 'Report generation and export'],
  ['SUPPORT_CASE_SERVICE', 'backend', 'Customer support case service', 'Operational investigations and recovery', 'life-buoy', 'Java', 'Operational case management'],
  ['POSTGRESQL', 'database', 'Customer operations database', 'Profiles cases disputes schedules', 'database'],
  ['COCKROACHDB', 'database', 'Multi-region ledger database', 'Serializable regional money state', 'database'],
  ['REDIS', 'database', 'Idempotency and rate-limit cache', 'Duplicate protection and hot limits', 'database'],
  ['CLICKHOUSE', 'database', 'Compliance analytics warehouse', 'Fraud and regulatory analytics', 'database'],
  ['KAFKA', 'queue', 'Transaction event stream', 'Durable ordered workflow events', 'message-square'],
  ['DEAD_LETTER_QUEUE', 'queue', 'Dead-letter recovery queue', 'Failed event replay and diagnosis', 'message-square-warning'],
  ['S3', 'storage', 'Encrypted document storage', 'KYC evidence and statements', 'hard-drive'],
  ['AUDIT_ARCHIVE', 'storage', 'Immutable audit archive', 'WORM retention across regions', 'archive'],
  ['PLAID', 'external', 'Bank account network', 'Account linking and bank rails', 'landmark'],
  ['STRIPE', 'external', 'Payment processor', 'Card and payment provider', 'credit-card'],
  ['CARD_NETWORKS', 'external', 'Card network integrations', 'Authorization and settlement rails', 'network'],
  ['IDENTITY_VERIFICATION', 'external', 'Identity verification provider', 'Document and biometric checks', 'scan-face'],
  ['TWILIO', 'external', 'Notification delivery provider', 'SMS and recovery messages', 'phone'],
  ['CLOUDFLARE', 'devops', 'Global edge and WAF', 'Regional routing and DDoS controls', 'cloud'],
  ['KUBERNETES', 'devops', 'Active-active regional runtime', 'Failover data residency and recovery', 'cloud-cog'],
  ['VAULT', 'devops', 'Encryption and secrets control', 'Keys tokens and PCI boundaries', 'shield'],
  ['ARGOCD', 'devops', 'Zero-downtime delivery', 'Progressive regional deployments', 'git-branch'],
  ['PROMETHEUS', 'devops', 'Metrics and alerting', 'SLOs saturation and failures', 'activity'],
  ['GRAFANA', 'devops', 'Operations dashboards', 'Cross-region service visibility', 'bar-chart']
];

const DIGITAL_BANKING_EDGES = [
  ['KOTLIN', 'API_GATEWAY', 'HTTPS'],
  ['SWIFT', 'API_GATEWAY', 'HTTPS'],
  ['REACT', 'API_GATEWAY', 'HTTPS'],
  ['OPERATIONS_CONSOLE', 'API_GATEWAY', 'HTTPS'],
  ['KOTLIN', 'KEYCLOAK', 'OIDC'],
  ['SWIFT', 'KEYCLOAK', 'OIDC'],
  ['REACT', 'KEYCLOAK', 'OIDC'],
  ['CLOUDFLARE', 'API_GATEWAY', 'HTTPS'],
  ['KUBERNETES', 'API_GATEWAY', 'HTTP'],
  ['ARGOCD', 'KUBERNETES', 'HTTPS'],
  ['API_GATEWAY', 'KEYCLOAK', 'OIDC'],
  ['API_GATEWAY', 'CUSTOMER_PROFILE_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'WALLET_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'CARD_AUTHORIZATION_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'TRANSFER_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'PAYMENT_ORCHESTRATOR', 'gRPC'],
  ['API_GATEWAY', 'DISPUTE_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'SCHEDULED_PAYMENTS_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'SUPPORT_CASE_SERVICE', 'gRPC'],
  ['API_GATEWAY', 'REDIS', 'TCP'],
  ['API_GATEWAY', 'VAULT', 'HTTPS'],
  ['CUSTOMER_PROFILE_SERVICE', 'POSTGRESQL', 'SQL'],
  ['CUSTOMER_PROFILE_SERVICE', 'S3', 'S3'],
  ['CUSTOMER_PROFILE_SERVICE', 'IDENTITY_VERIFICATION', 'HTTPS'],
  ['CUSTOMER_PROFILE_SERVICE', 'KAFKA', 'KAFKA'],
  ['WALLET_SERVICE', 'LEDGER_SERVICE', 'gRPC'],
  ['WALLET_SERVICE', 'REDIS', 'TCP'],
  ['WALLET_SERVICE', 'KAFKA', 'KAFKA'],
  ['LEDGER_SERVICE', 'COCKROACHDB', 'SQL'],
  ['LEDGER_SERVICE', 'AUDIT_LOG_SERVICE', 'gRPC'],
  ['LEDGER_SERVICE', 'KAFKA', 'KAFKA'],
  ['LEDGER_SERVICE', 'VAULT', 'HTTPS'],
  ['CARD_AUTHORIZATION_SERVICE', 'FRAUD_ENGINE', 'gRPC'],
  ['CARD_AUTHORIZATION_SERVICE', 'CARD_NETWORKS', 'HTTPS'],
  ['CARD_AUTHORIZATION_SERVICE', 'LEDGER_SERVICE', 'gRPC'],
  ['CARD_AUTHORIZATION_SERVICE', 'KAFKA', 'KAFKA'],
  ['TRANSFER_SERVICE', 'COMPLIANCE_SERVICE', 'gRPC'],
  ['TRANSFER_SERVICE', 'FRAUD_ENGINE', 'gRPC'],
  ['TRANSFER_SERVICE', 'LEDGER_SERVICE', 'gRPC'],
  ['TRANSFER_SERVICE', 'PLAID', 'HTTPS'],
  ['TRANSFER_SERVICE', 'KAFKA', 'KAFKA'],
  ['PAYMENT_ORCHESTRATOR', 'FRAUD_ENGINE', 'gRPC'],
  ['PAYMENT_ORCHESTRATOR', 'STRIPE', 'HTTPS'],
  ['PAYMENT_ORCHESTRATOR', 'LEDGER_SERVICE', 'gRPC'],
  ['PAYMENT_ORCHESTRATOR', 'KAFKA', 'KAFKA'],
  ['FRAUD_ENGINE', 'REDIS', 'TCP'],
  ['FRAUD_ENGINE', 'CLICKHOUSE', 'SQL'],
  ['FRAUD_ENGINE', 'KAFKA', 'KAFKA'],
  ['COMPLIANCE_SERVICE', 'CLICKHOUSE', 'SQL'],
  ['COMPLIANCE_SERVICE', 'IDENTITY_VERIFICATION', 'HTTPS'],
  ['COMPLIANCE_SERVICE', 'KAFKA', 'KAFKA'],
  ['DISPUTE_SERVICE', 'POSTGRESQL', 'SQL'],
  ['DISPUTE_SERVICE', 'STRIPE', 'HTTPS'],
  ['DISPUTE_SERVICE', 'S3', 'S3'],
  ['DISPUTE_SERVICE', 'KAFKA', 'KAFKA'],
  ['SCHEDULED_PAYMENTS_SERVICE', 'POSTGRESQL', 'SQL'],
  ['SCHEDULED_PAYMENTS_SERVICE', 'PAYMENT_ORCHESTRATOR', 'gRPC'],
  ['SCHEDULED_PAYMENTS_SERVICE', 'KAFKA', 'KAFKA'],
  ['KAFKA', 'NOTIFICATION_SERVICE', 'KAFKA'],
  ['KAFKA', 'AUDIT_LOG_SERVICE', 'KAFKA'],
  ['KAFKA', 'RECONCILIATION_SERVICE', 'KAFKA'],
  ['KAFKA', 'REPORTING_SERVICE', 'KAFKA'],
  ['KAFKA', 'SUPPORT_CASE_SERVICE', 'KAFKA'],
  ['KAFKA', 'DEAD_LETTER_QUEUE', 'KAFKA'],
  ['DEAD_LETTER_QUEUE', 'RECONCILIATION_SERVICE', 'KAFKA'],
  ['NOTIFICATION_SERVICE', 'TWILIO', 'HTTPS'],
  ['NOTIFICATION_SERVICE', 'POSTGRESQL', 'SQL'],
  ['AUDIT_LOG_SERVICE', 'AUDIT_ARCHIVE', 'S3'],
  ['RECONCILIATION_SERVICE', 'COCKROACHDB', 'SQL'],
  ['RECONCILIATION_SERVICE', 'STRIPE', 'HTTPS'],
  ['RECONCILIATION_SERVICE', 'PLAID', 'HTTPS'],
  ['RECONCILIATION_SERVICE', 'KAFKA', 'KAFKA'],
  ['REPORTING_SERVICE', 'CLICKHOUSE', 'SQL'],
  ['REPORTING_SERVICE', 'AUDIT_ARCHIVE', 'S3'],
  ['SUPPORT_CASE_SERVICE', 'POSTGRESQL', 'SQL'],
  ['API_GATEWAY', 'PROMETHEUS', 'HTTP'],
  ['LEDGER_SERVICE', 'PROMETHEUS', 'HTTP'],
  ['KAFKA', 'PROMETHEUS', 'HTTP'],
  ['COCKROACHDB', 'PROMETHEUS', 'HTTP'],
  ['KUBERNETES', 'PROMETHEUS', 'HTTP'],
  ['PROMETHEUS', 'GRAFANA', 'HTTP']
];

function createNode([name, category, role, reason, icon, implementation, implementationDescription]) {
  return {
    name,
    category,
    role,
    reason,
    icon,
    implementation,
    implementationDescription
  };
}

function createEdge([source, target, label]) {
  return { source, target, label };
}

export function applyDigitalBankingBlueprint() {
  return {
    diagram: {
      nodes: DIGITAL_BANKING_NODES.map(createNode),
      edges: DIGITAL_BANKING_EDGES.map(createEdge)
    },
    changes: [
      'Domain tuned: expanded digital banking service boundaries',
      'Domain tuned: added strict ledger, idempotency, and recovery paths',
      'Domain tuned: added multi-region security, compliance, and operations controls'
    ]
  };
}
